version: '3'
services:
    web:
        image: nginx:latest
        ports:
          - "80:80"
          - "443:443"
        volumes:
          - "${SOURCE_DIR}:${CONTAINER_DIR}"
          - "./Docker/nginx/conf:/etc/nginx/conf.d/"
        depends_on:
          - php

    mysql:
        image: mysql:8
        volumes:
            - "${DATABASE_DIR}:/var/lib/mysql"
        command:
            - "--default-authentication-plugin=mysql_native_password"
            - "--lower_case_table_names=1"
        environment:
            MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
            MYSQL_DATABASE: "${MYSQL_DATABASE}"
            MYSQL_USER: "${MYSQL_USER}"
            MYSQL_PASSWORD: "${MYSQL_PASSWORD}"

    php:
        image: jcarlosjl/webpage
        build: Docker/php
        volumes:
          - "${SOURCE_DIR}:${CONTAINER_DIR}"
        environment: 
          APP_ENV: "${APP_ENV}"
        depends_on:
          - mysql
    composer:
        image: composer
        command: ["composer", "install", "--no-interaction"]
        volumes: 
          - "${SOURCE_DIR}:/app"